import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import StoreProvider from './StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Мультимедийный центр теплоэнергетики</title>
      <body className={inter.className}>
        <main>
          <div className="main-content">
            <StoreProvider>{children}</StoreProvider>
          </div>
        </main>
      </body>
    </html>
  );
}
